branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - tarballDir: dist
  - - "@semantic-release/github"
    - successComment: false
      failComment: false
      assets: "dist/*.tgz"
